module.exports = {
  SUCCESS: true,
  FAILURE: false,
  S3_BUCKET: "sidebrain-mumbai",
  S3_BUCKET_ENDPOINT: "https://sidebrain-mumbai.s3.ap-south-1.amazonaws.com/",
  LINK: "LINK",
  TEXT: "TEXT",
  SALT_ROUNDS: 10,
  ALREADY_EXISTS: "Email id already exists.",
  NOT_EXISTS: "User Not exists.",
  INVALID_CREDENTIALS: "Invalid credentials",
  INVALID_OTP: "Invalid OTP",
  EXPIRED_OTP: "Expired OTP",
  LIMIT: 20,
  UNKNOWN_OPERATION: "unknown operation",
  UNKNOWN_CART_ITEM: "unknown cart item",
  INVALID_TOKEN: "May be provide token is invalid or session expired",
  INVALID_ADDRESS_ID: "Invalid Address ID!",
  EMPTY_CART: "Cart is empty!",
  UPDATE_RESTRICTED: "Update restricted",
  TOKEN_MISSING: "No token provided!",
};
